# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.26.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.26.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/bemen/Documents/AUC/22_23/Spring/CSCE 2303/RISC-V_Simulator"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/bemen/Documents/AUC/22_23/Spring/CSCE 2303/RISC-V_Simulator"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.26.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.26.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/bemen/Documents/AUC/22_23/Spring/CSCE 2303/RISC-V_Simulator/CMakeFiles" "/Users/bemen/Documents/AUC/22_23/Spring/CSCE 2303/RISC-V_Simulator//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/bemen/Documents/AUC/22_23/Spring/CSCE 2303/RISC-V_Simulator/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RISC-V_Simulator

# Build rule for target.
RISC-V_Simulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RISC-V_Simulator
.PHONY : RISC-V_Simulator

# fast build rule for target.
RISC-V_Simulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISC-V_Simulator.dir/build.make CMakeFiles/RISC-V_Simulator.dir/build
.PHONY : RISC-V_Simulator/fast

# target to build an object file
src_copy/genUtils.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISC-V_Simulator.dir/build.make CMakeFiles/RISC-V_Simulator.dir/src_copy/genUtils.o
.PHONY : src_copy/genUtils.o

# target to preprocess a source file
src_copy/genUtils.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISC-V_Simulator.dir/build.make CMakeFiles/RISC-V_Simulator.dir/src_copy/genUtils.i
.PHONY : src_copy/genUtils.i

# target to generate assembly for a file
src_copy/genUtils.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISC-V_Simulator.dir/build.make CMakeFiles/RISC-V_Simulator.dir/src_copy/genUtils.s
.PHONY : src_copy/genUtils.s

# target to build an object file
src_copy/memory.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISC-V_Simulator.dir/build.make CMakeFiles/RISC-V_Simulator.dir/src_copy/memory.o
.PHONY : src_copy/memory.o

# target to preprocess a source file
src_copy/memory.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISC-V_Simulator.dir/build.make CMakeFiles/RISC-V_Simulator.dir/src_copy/memory.i
.PHONY : src_copy/memory.i

# target to generate assembly for a file
src_copy/memory.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISC-V_Simulator.dir/build.make CMakeFiles/RISC-V_Simulator.dir/src_copy/memory.s
.PHONY : src_copy/memory.s

# target to build an object file
src_copy/test.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISC-V_Simulator.dir/build.make CMakeFiles/RISC-V_Simulator.dir/src_copy/test.o
.PHONY : src_copy/test.o

# target to preprocess a source file
src_copy/test.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISC-V_Simulator.dir/build.make CMakeFiles/RISC-V_Simulator.dir/src_copy/test.i
.PHONY : src_copy/test.i

# target to generate assembly for a file
src_copy/test.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISC-V_Simulator.dir/build.make CMakeFiles/RISC-V_Simulator.dir/src_copy/test.s
.PHONY : src_copy/test.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RISC-V_Simulator"
	@echo "... src_copy/genUtils.o"
	@echo "... src_copy/genUtils.i"
	@echo "... src_copy/genUtils.s"
	@echo "... src_copy/memory.o"
	@echo "... src_copy/memory.i"
	@echo "... src_copy/memory.s"
	@echo "... src_copy/test.o"
	@echo "... src_copy/test.i"
	@echo "... src_copy/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

